---
title: "Day 3 - Conditionals & Loops"
author: "Guillermo Romero"
date: "2022-08-10"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
library(tidyverse)
library(palmerpenguins)
```


# `if` statements

```{r}
burrito <- 2
if (burrito > 2) {
  print("I Love Burritos!")
}
```

# `String_detect()`
```{r}
my_ships <- c("Millenium Falcon", "X-Wing","Tie Fighter","Death Star")
str_detect(my_ships, pattern = "r")
# Case sensitive, can use function to turn everything lowercase or uppercase
str_detect(my_ships, pattern = "x")

phrase <- "I love burritos!"
if (str_detect(phrase, "love")) {
  print("I am burrito fan")
}
```
```{r}
tatooine_characters <- starwars |> 
  filter(homeworld == "Tatooine")
```

# Use  %in% operator to check for multiple positive matches
```{r}
tatooine_endor_naboo1 <- starwars |> filter(homeworld == "Tatooine" | homeworld == "Naboo" | homeworld == "Endor")

tatooine_endor_naboo2 <- starwars |> filter(homeworld %in% c("Tatooine","Naboo","Endor"))
```

# `if-else statement`

```{r}
pika <- 89.1

if (pika > 60) {
  print("mega pika")
}else{
  print("normal pika")
}
```

```{r}
marmot <- 2.8

if (marmot < 0.5) {
  print("this is a small marmot")
}else if (marmot >= 0.5 & marmot <3){
  print("this is a medium marmot")
}else{
  print("this is a large marmot")
}
```
# For Loops
```{r}
tree_height <- c(1, 2, 6, 10, 14, 20)

for (i in seq_along(tree_height)){
  val = tree_height[i] + tree_height[i + 1]
  print(val)
}
```

```{r}
# convert human age to animal years, conversion factor depends on the type animal

species <- c("dog", "elephant", "goat", "dog", "dog", "elephant")
age_human <- c(3, 8, 4, 6, 12, 18)

animal_ages <- vector(mode = "numeric", length = length(species))

for (i in seq_along(species)){
  if (species[i] == "dog"){
    animal_age <- age_human[i] * 7
  }else if (species[i] == "elephant"){
    animal_age <- age_human[i] * 0.88
  }else if (species[i] == "goat"){
    animal_age <- age_human[i] * 4.7
  }
  animal_ages[i] <- animal_age
}
```

# `group_by() |>  summarize ()`

```{r}
penguins |> 
  group_by(species,island) |> 
  summarize(mean_bill_length = mean(bill_length_mm, na.rm = TRUE),
            sd_bill_length = sd(bill_length_mm, na.rm = TRUE),
            n = n())
# groupby R now knows that whatever you want to do next will be done by group
#summarize() whatever function you give it will be applied to each group and returned as a summary table
# mean_bill_length is returned a new column for the values
# Nested grouping, so break up by species and island, group(species,island)
# 'n()' to count everything including rows that were NA
```

```{r}
# Find the mean and sd of character height in "starwars" grouped by homeworld
starwars |> 
  group_by(homeworld) |> 
  summarize(mean_character_height = mean(height, na.rm = TRUE),
            sd_character_height = sd(height, na.rm = TRUE))



# Find the max, min flipper length, and sample size, for each species of penguins

penguins |> 
  group_by(species,sex) |> 
  summarize(max_flipper_length = max(flipper_length_mm, na.rm = TRUE),
            min_flipper_length = mean(flipper_length_mm, na.rm = TRUE),
            n = n())
# across() columns that satisfy our condition then apply the function for those columns
penguins |> 
  group_by(species) |> 
  summarize(across(where(is.numeric), mean, na.rm = TRUE))

#mutate()create these columns where 
penguins |> 
  mutate(across(c(species, island),toupper))

```

### For Loops `Across()` Data Frames

```{r}
mean_mtcars <- vector(mode = "numeric", length = ncol(mtcars))

for (i in seq_along(mtcars)){
  mean_value <- mean(mtcars[[i]], na.rm = TRUE)
  mean_mtcars[i] <- mean_value
}
mean_mtcars
```

# Functional Programming examples

Adding syntatic sugar (apply, across, map_df)

```{r}
# Calculating the mean of every column
apply(X = mtcars, MARGIN = 2, FUN = mean)

```

```{r}
# Purr

map(.x = mtcars, .f = mean)
#map_
```

